# Krisha.kz Scraper Configuration
# This file defines search queries for both rental and sales flats

# Database configuration
[database]
path = "flats.db"

# Scraping configuration
[scraping]
delay_between_requests = 2.0  # seconds
max_flats_per_query = 50      # maximum flats to scrape per query
retry_attempts = 3            # number of retry attempts for failed requests

# Search queries for rentals
[[rental_queries]]
name = "Meridian Apartments - 1 room rentals"
description = "1-room apartments for rent in Meridian Apartments, Almaty"
url = "https://krisha.kz/arenda/kvartiry/almaty/?das[live.rooms]=1&das[map.complex]=2758"
parameters = { rooms = 1, complex_id = "2758", area_max = 35 }

[[rental_queries]]
name = "Meridian Apartments - 2 room rentals"
description = "2-room apartments for rent in Meridian Apartments, Almaty"
url = "https://krisha.kz/arenda/kvartiry/almaty/?das[live.rooms]=2&das[map.complex]=2758"
parameters = { rooms = 2, complex_id = "2758", area_max = 50 }

[[rental_queries]]
name = "Meridian Apartments - 3 room rentals"
description = "3-room apartments for rent in Meridian Apartments, Almaty"
url = "https://krisha.kz/arenda/kvartiry/almaty/?das[live.rooms]=3&das[map.complex]=2758"
parameters = { rooms = 3, complex_id = "2758", area_max = 80 }

# Search queries for sales
[[sales_queries]]
name = "Meridian Apartments - 1 room sales"
description = "1-room apartments for sale in Meridian Apartments, Almaty"
url = "https://krisha.kz/prodazha/kvartiry/almaty/?das[live.rooms]=1&das[map.complex]=2758"
parameters = { rooms = 1, complex_id = "2758", area_max = 35 }

[[sales_queries]]
name = "Meridian Apartments - 2 room sales"
description = "2-room apartments for sale in Meridian Apartments, Almaty"
url = "https://krisha.kz/prodazha/kvartiry/almaty/?das[live.rooms]=2&das[map.complex]=2758"
parameters = { rooms = 2, complex_id = "2758", area_max = 50 }

[[sales_queries]]
name = "Meridian Apartments - 3 room sales"
description = "3-room apartments for sale in Meridian Apartments, Almaty"
url = "https://krisha.kz/prodazha/kvartiry/almaty/?das[live.rooms]=3&das[map.complex]=2758"
parameters = { rooms = 3, complex_id = "2758", area_max = 80 }

# Additional search queries can be added here
# Example for different complexes:
# [[rental_queries]]
# name = "Another Complex - 1 room rentals"
# description = "1-room apartments for rent in Another Complex, Almaty"
# url = "https://krisha.kz/arenda/kvartiry/almaty/?das[live.rooms]=1&das[map.complex]=1234"
# parameters = { rooms = 1, complex_id = "1234", area_max = 35 }

# Scheduling configuration
[scheduling]
enabled = true
interval_hours = 24  # run every 24 hours
start_time = "09:00"  # start time for daily runs
timezone = "Asia/Almaty"

# Logging configuration
[logging]
level = "INFO"  # DEBUG, INFO, WARNING, ERROR
file = "scraper.log"
max_size_mb = 10
backup_count = 5 